[".oh-my-zsh"]
  type = "archive"
  url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/fzf-zsh-plugin"]
  type = "archive"
  url = "https://github.com/unixorn/fzf-zsh-plugin/archive/main.tar.gz"
  exact = true
  stripComponents = 1
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
  exact = true
  stripComponents = 1
[".oh-my-zsh/custom/plugins/zsh-fzf-history-search"]
  type = "archive"
  url = "http://github.com/joshskidmore/zsh-fzf-history-search/archive/master.tar.gz"
  exact = true
  stripComponents = 1
[".oh-my-zsh/custom/plugins/zsh-completions"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-completions/archive/master.tar.gz"
  exact = true
  stripComponents = 1
